name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: asdf
      id: asdf
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: asdf
        setup-command: "./setup.sh"
        command: "./calc.sh"
        input: 1+1
        expected-output: '2'
        comparison-method: exact
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASDF_RESULTS: "${{steps.asdf.outputs.result}}"
      with:
        runners: asdf
